# Generated by Django 2.1.5 on 2019-01-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='text_decription',
            new_name='text_description',
        ),
    ]
